### PR TITLE
Fixes basemap issue

### PR DESCRIPTION
**Pull request by pwolfram**
Bug fix to resolve issues following from https://github.com/MPAS-Dev/MPAS-Model/pull/441 as identified in https://github.com/MPAS-Dev/MPAS-Model/issues/475

### CODE REVIEW

**Comment by xylar** [comment]
@vanroekel also has a notebook using basemap: https://github.com/MPAS-Dev/MPAS-QuickViz/blob/master/ocean/enso_composites/ensoComposites.ipynb

I guess that can get updated later, though, depending on how it's getting used (e.g. at NERSC vs. LANL and with E3SM-Unified vs. COMPASS envs.).

**Comment by pwolfram** [comment]
# Test

**Comment by pwolfram** [comment]
Thanks @xylar, opened #5 to keep track of this issue.

**Comment by vanroekel** [comment]
@xylar don't worry about the ENSO composites notebook.  If I need that analysis again I will convert to cartopy then.

**Pull request merged**
