### PR TITLE
Adds transect plot capability

### PR DESCRIPTION
**Pull request by pwolfram**
Plots transects for low / high-res following post-processing.

transport_figure

### CODE REVIEW

**Review by mark-petersen — APPROVED** [review]
Looks great!  

I'm happy to be notified, but FYI, for QuickViz making a PR versus just merging is at your discretion.

**Review by vanroekel — APPROVED** [review]
looks good!  Feel free to merge

**Comment by pwolfram** [comment]
Thanks @vanroekel!

**Comment by pwolfram** [comment]
Thanks @mark-petersen!

**Pull request merged**
